<feature> 주문창 구현
ys0221/Kiosk---Team2 pull request #8
Opened 2024-07-15 13:01 UTC by ys0221

## #️⃣연관된 이슈
> ex) `#이슈번호, #이슈번호`</br>
> 해당 PR이 닫힐 때, 이슈도 닫히게 하고싶다면? ex) `close #이슈번호, #이슈번호`

- 

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- order 창에서 1번 누르면 요청 사항 작성한 후 대기번호 부여하는 기능 구현

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

-

2024-07-17 04:44 UTC, jwb03 approved these changes
고생하셨습니다!

2024-07-17 04:56 UTC, yjsmk0902 requested changes
추가된 코드의 상황에서 대부분 변수 명명 규칙에 대한 통일이 이루어지지 않고 있다는 생각이 들어, 케이스의 통일이 필요해 보입니다. 

자세한 사항은 코멘트에 관련 링크 달아놨으니 한번 확인해 주시면 감사하겠습니다👍

고생하셨습니다👏👏

2024-07-17 04:56 UTC, yjsmk0902 commented on src/Main.java
> +        ArrayList<String> order_requests = new ArrayList<>();
스네이크 케이스의 카멜 케이스로 변경이 필요해 보입니다. 통일된 케이스 사용해주세요!

[카멜 케이스와 파스칼 케이스](https://ccomccomhan.tistory.com/m/185)

2024-07-17 04:56 UTC, yjsmk0902 commented on src/Manage.java
> +    public Manage(List<Double> price, List<String> list1, List<Product> list2) {
파라미터를 list1, list2로 받는 것보다는 파라미터로 요소를 알아볼 수 있도록 네이밍 해주는 것이 어떨까 생각합니다.

2024-07-18 05:57 UTC, yjsmk0902 approved these changes
고생하셨습니다👏👏👏

2024-07-20 03:25 UTC, jinpark00 approved these changes

2024-07-20 16:02 UTC, merged